spring.application.name=campus-events

# locale
spring.web.locale-resolver=FIXED 
spring.web.locale=pt-BR

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/campusevents
spring.datasource.username=postgres
spring.datasource.password=@Joao123
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA / Hibernate  
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
   
